on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest

    steps:
      - name: Hello world action step
        uses: SRE-Avinash/customAction-JS/@0.0.2
        id: hello
        with:
          name: 'Avinash'

      # Use the output from the `hello` step
      - name: Get the output 
        run: echo "The time was ${{ steps.hello.outputs.greeting }}"

      - name: 
