name: Context-example

on: [ 'push' ]

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My Step"
        run: echo "Hello! $MY_ACTION"
        env:
          My_ACTION: ${{ github.action }}
      - name: Print github.actor
        env:
          MY_ACTOR: ${{ github.actor }}
        run: echo "Triggered by $MY_ACTOR"

